### ISSUE TITLE
Empty string instead of null for workflow input

### ISSUE THREAD

**Issue by michael-kotliar** [datirium/scidap#10]
When you click on an automatically generated form to set value for input `extension_size` or write and remove this value, the generated job will have `""` for this input and workflow will fail. 
```
extension_size:
  type:
    - "null"
    - int[]
  label: "Read's extension size"
```
Workflow to test
https://github.com/datirium/workflows/blob/3ab3053ab80f477198c009bbc7e929f474dfaff1/workflows/rgt-thor.cwl#L102

**Comment by michael-kotliar** [comment]
A similar situation happens with the following input from the same `rgt-thor.cwl` pipeline
```
  pvalue_cutoff:
    type: float?
    label: "P-value cutoff for peak detection"
    doc: "P-value cutoff for peak detection. Call only peaks with p-value lower than cutoff. [default: 0.1]"
    'sd:layout':
      advanced: true
```
If the correspondent field on a form is updated (clicked, removed), the value is set to 0

**Comment by carcassona** [comment]
```
  pvalue_cutoff:
    type: float?
    default: 0.1
    label: "P-value cutoff for peak detection"
    doc: "P-value cutoff for peak detection. Call only peaks with p-value lower than cutoff. [default: 0.1]"
    'sd:layout':
      advanced: true
```

The code looks liked this now, and the question is, if 0 is forbidden should we have kind a range param for the value?
