### ISSUE TITLE
Markdown visual plugin

### ISSUE THREAD

**Issue by michael-kotliar** [datirium/scidap#16]
It would be nice to have a simple way to render markdown files.

For example:
```yaml
  get_stat_markdown:
    type: File?
    label: "Markdown formatted combined log"
    format: "http://edamontology.org/format_3835"
    doc: "Markdown formatted combined log"
    outputSource: get_stat/collected_statistics_md
    'sd:visualPlugins':
    - markdownView:
        tab: 'Overview'
```
