### ISSUE TITLE
Image visual plugin for array of Files

### ISSUE THREAD

**Issue by michael-kotliar** [datirium/scidap#23]
It looks like for output with type`File[]` the visual plugin `image` doesn't work.

```yaml
  gseapy_enrichment_plots:
    type: File[]
    format: "http://edamontology.org/format_3508"
    label: "Enrichment plots"
    doc: "Enrichment plots"
    outputSource: run_gseapy/enrichment_plots
    "sd:visualPlugins":
    - image:
        tab: "Plots"
        Caption: "Enrichment plot"
```
