### ISSUE TITLE
Use alias from upstream analysis as workflow input

### ISSUE THREAD

**Issue by michael-kotliar** [datirium/scidap#6]
It would be nice to have something like this 
```yaml
  legend_name:
    type:
      - "null"
      - string[]
    label: "Isoform expression file aliases"
    doc: "Aliases to make the legend for generated plots. Order corresponds to the isoform expression files"
    'sd:upstreamSource': "rnaseq_sample/alias"
    'sd:localLabel': true
```
Currently, only actual workflow input can be used as upstream source, whereas `alias` comes from `sd:metadata` of the upstream analysis.

See this as a workflow example
https://github.com/datirium/workflows/blob/7518b100d8cbc80c8be32e9e939dfbb27d6b4361/workflows/pca.cwl#L35
